---
- name: "Pod Status Check"
  hosts: localhost
  gather_facts: no
  ignore_errors: true
  collections:
    - kubernetes.core
  tasks:
    - name: "Login first"
      shell: |
        oc login --token={{apikey}} --server=https://api.aap-test-v416-x86-64-ljrbm.ocp4.testing.ansible.com:6443
      args:
        executable: /bin/bash
      async: 30
      poll: 10
      register: "output"
    - name: Get Cluster information
      kubernetes.core.k8s_cluster_info:
      register: cluster_information
    - name: Get pods information
      kubernetes.core.k8s_info:
        kubeconfig: "~/.kube/config"
        username: kubeadmin
        password: "{{apikey}}"
        kind: Pod
      register: pods_info
